name: Handle issues
on: issues

jobs:
    output-event:
        runs-on: ubuntu-latest
        steps:
            - name: Output event details
              run: echo "${{ toJson(github.event) }}"
